version = "1.0.${BUILD_NUMBER}"

node {
    stage ('Build Image') {
        checkout scm
        withCredentials([
            usernamePassword(credentialsId: 'docker-hub', usernameVariable: 'username', passwordVariable: 'password')
        ]) {
            sh(script: "docker login ${registry_url} -u ${username} -p ${password}")
            sh "docker build -t unionized-api:${version} -f Dockerfile"
        }
    }
    stage ('Push to Docker Hub') {
        sh "docker push unionized-api:${version}"
    }
}