/*
 * openHAB REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;

using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace Unionized.Model.OpenHab
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class DiscoveryResultDTO : IEquatable<DiscoveryResultDTO>
    { 
        /// <summary>
        /// Gets or Sets BridgeUID
        /// </summary>
        [DataMember(Name="bridgeUID")]
        public string BridgeUID { get; set; }

        /// <summary>
        /// Gets or Sets Flag
        /// </summary>
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum FlagEnum
        {
            
            /// <summary>
            /// Enum NEWEnum for NEW
            /// </summary>
            [EnumMember(Value = "NEW")]
            NEWEnum = 1,
            
            /// <summary>
            /// Enum IGNOREDEnum for IGNORED
            /// </summary>
            [EnumMember(Value = "IGNORED")]
            IGNOREDEnum = 2
        }

        /// <summary>
        /// Gets or Sets Flag
        /// </summary>
        [DataMember(Name="flag")]
        public FlagEnum? Flag { get; set; }

        /// <summary>
        /// Gets or Sets Label
        /// </summary>
        [DataMember(Name="label")]
        public string Label { get; set; }

        /// <summary>
        /// Gets or Sets Properties
        /// </summary>
        [DataMember(Name="properties")]
        public Dictionary<string, Object> Properties { get; set; }

        /// <summary>
        /// Gets or Sets RepresentationProperty
        /// </summary>
        [DataMember(Name="representationProperty")]
        public string RepresentationProperty { get; set; }

        /// <summary>
        /// Gets or Sets ThingUID
        /// </summary>
        [DataMember(Name="thingUID")]
        public string ThingUID { get; set; }

        /// <summary>
        /// Gets or Sets ThingTypeUID
        /// </summary>
        [DataMember(Name="thingTypeUID")]
        public string ThingTypeUID { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class DiscoveryResultDTO {\n");
            sb.Append("  BridgeUID: ").Append(BridgeUID).Append("\n");
            sb.Append("  Flag: ").Append(Flag).Append("\n");
            sb.Append("  Label: ").Append(Label).Append("\n");
            sb.Append("  Properties: ").Append(Properties).Append("\n");
            sb.Append("  RepresentationProperty: ").Append(RepresentationProperty).Append("\n");
            sb.Append("  ThingUID: ").Append(ThingUID).Append("\n");
            sb.Append("  ThingTypeUID: ").Append(ThingTypeUID).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((DiscoveryResultDTO)obj);
        }

        /// <summary>
        /// Returns true if DiscoveryResultDTO instances are equal
        /// </summary>
        /// <param name="other">Instance of DiscoveryResultDTO to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(DiscoveryResultDTO other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    BridgeUID == other.BridgeUID ||
                    BridgeUID != null &&
                    BridgeUID.Equals(other.BridgeUID)
                ) && 
                (
                    Flag == other.Flag ||
                    Flag != null &&
                    Flag.Equals(other.Flag)
                ) && 
                (
                    Label == other.Label ||
                    Label != null &&
                    Label.Equals(other.Label)
                ) && 
                (
                    Properties == other.Properties ||
                    Properties != null &&
                    Properties.SequenceEqual(other.Properties)
                ) && 
                (
                    RepresentationProperty == other.RepresentationProperty ||
                    RepresentationProperty != null &&
                    RepresentationProperty.Equals(other.RepresentationProperty)
                ) && 
                (
                    ThingUID == other.ThingUID ||
                    ThingUID != null &&
                    ThingUID.Equals(other.ThingUID)
                ) && 
                (
                    ThingTypeUID == other.ThingTypeUID ||
                    ThingTypeUID != null &&
                    ThingTypeUID.Equals(other.ThingTypeUID)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (BridgeUID != null)
                    hashCode = hashCode * 59 + BridgeUID.GetHashCode();
                    if (Flag != null)
                    hashCode = hashCode * 59 + Flag.GetHashCode();
                    if (Label != null)
                    hashCode = hashCode * 59 + Label.GetHashCode();
                    if (Properties != null)
                    hashCode = hashCode * 59 + Properties.GetHashCode();
                    if (RepresentationProperty != null)
                    hashCode = hashCode * 59 + RepresentationProperty.GetHashCode();
                    if (ThingUID != null)
                    hashCode = hashCode * 59 + ThingUID.GetHashCode();
                    if (ThingTypeUID != null)
                    hashCode = hashCode * 59 + ThingTypeUID.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(DiscoveryResultDTO left, DiscoveryResultDTO right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(DiscoveryResultDTO left, DiscoveryResultDTO right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
