/*
 * openHAB REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;

using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace Unionized.Model.OpenHab
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class ItemHistoryDTO : IEquatable<ItemHistoryDTO>
    { 
        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name="name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets Totalrecords
        /// </summary>
        [DataMember(Name="totalrecords")]
        public string Totalrecords { get; set; }

        /// <summary>
        /// Gets or Sets Datapoints
        /// </summary>
        [DataMember(Name="datapoints")]
        public string Datapoints { get; set; }

        /// <summary>
        /// Gets or Sets Data
        /// </summary>
        [DataMember(Name="data")]
        public List<HistoryDataBean> Data { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ItemHistoryDTO {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Totalrecords: ").Append(Totalrecords).Append("\n");
            sb.Append("  Datapoints: ").Append(Datapoints).Append("\n");
            sb.Append("  Data: ").Append(Data).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((ItemHistoryDTO)obj);
        }

        /// <summary>
        /// Returns true if ItemHistoryDTO instances are equal
        /// </summary>
        /// <param name="other">Instance of ItemHistoryDTO to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ItemHistoryDTO other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Name == other.Name ||
                    Name != null &&
                    Name.Equals(other.Name)
                ) && 
                (
                    Totalrecords == other.Totalrecords ||
                    Totalrecords != null &&
                    Totalrecords.Equals(other.Totalrecords)
                ) && 
                (
                    Datapoints == other.Datapoints ||
                    Datapoints != null &&
                    Datapoints.Equals(other.Datapoints)
                ) && 
                (
                    Data == other.Data ||
                    Data != null &&
                    Data.SequenceEqual(other.Data)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Name != null)
                    hashCode = hashCode * 59 + Name.GetHashCode();
                    if (Totalrecords != null)
                    hashCode = hashCode * 59 + Totalrecords.GetHashCode();
                    if (Datapoints != null)
                    hashCode = hashCode * 59 + Datapoints.GetHashCode();
                    if (Data != null)
                    hashCode = hashCode * 59 + Data.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(ItemHistoryDTO left, ItemHistoryDTO right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(ItemHistoryDTO left, ItemHistoryDTO right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
