// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using Unionized.Model.API.HomeAssistant;
//
//    var state = State.FromJson(jsonString);
using System;
using System.Collections.Generic;

using Newtonsoft.Json;

using Unionized;

namespace Unionized.Model.API.HomeAssistant
{
    public abstract class HaState
    {
        [JsonProperty("attributes", Required = Required.Always)]
        public HaAttributes Attributes { get; set; }

        [JsonProperty("context", Required = Required.Always)]
        public HaContext Context { get; set; }

        [JsonProperty("entity_id", Required = Required.Always)]
        public string EntityId { get; set; }

        [JsonProperty("last_changed", Required = Required.Always)]
        public DateTimeOffset LastChanged { get; set; }

        [JsonProperty("last_updated", Required = Required.Always)]
        public DateTimeOffset LastUpdated { get; set; }

        [JsonProperty("state", Required = Required.Always)]
        public string State { get; set; }
    }
}
