CREATE TABLE IF NOT EXISTS `network_log` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `slug` VARCHAR(32) NOT NULL,
    `log_date` DATETIME NOT NULL,
    `rule` VARCHAR(16) NOT NULL,
    `iface_in` VARCHAR(8) NOT NULL,
    `iface_out` VARCHAR(8) NOT NULL,
    `mac_address` VARCHAR(32) NOT NULL,
    `src_address` VARCHAR(24) NOT NULL,
    `dst_address` VARCHAR(24) NOT NULL,
    `packet_len` INT NOT NULL,
    `ttl` INT NOT NULL,
    `protocol` VARCHAR(8) NOT NULL,
    `src_port` INT NULL,
    `dst_port` INT NULL,
    `tcp_action` VARCHAR(16) NULL,
    `icmp_sequence` INT NULL,
    `created_at` DATETIME NOT NULL,
    `updated_at` DATETIME NULL,
    `active` INT(1),
    INDEX (`slug` , `log_date` , `src_address` , `dst_address` , `src_port` , `dst_port` , `created_at`)
)